// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM4aOM7F3M4-P_9DC6m-W-_ykPYm432nY',
    appId: '1:948390414091:web:ad36d9b1dbda143aba040e',
    messagingSenderId: '948390414091',
    projectId: 'social-media-9c261',
    authDomain: 'social-media-9c261.firebaseapp.com',
    storageBucket: 'social-media-9c261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbBENq3w--1z9OnI_kV38IjWy3rwEV8U',
    appId: '1:948390414091:android:966cb3a36e0c4427ba040e',
    messagingSenderId: '948390414091',
    projectId: 'social-media-9c261',
    storageBucket: 'social-media-9c261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdEZrah9bAaMpZALU2Y5noecEbgECq6IE',
    appId: '1:948390414091:ios:8213aa0ae3783691ba040e',
    messagingSenderId: '948390414091',
    projectId: 'social-media-9c261',
    storageBucket: 'social-media-9c261.appspot.com',
    iosClientId: '948390414091-hpraeu0qugktrgvgmkpu4hmsi23732dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdEZrah9bAaMpZALU2Y5noecEbgECq6IE',
    appId: '1:948390414091:ios:8213aa0ae3783691ba040e',
    messagingSenderId: '948390414091',
    projectId: 'social-media-9c261',
    storageBucket: 'social-media-9c261.appspot.com',
    iosClientId: '948390414091-hpraeu0qugktrgvgmkpu4hmsi23732dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
